from lhereader import readLHEF
from ROOT import TCanvas, TH1F, TH2F
import math
data=readLHEF('FFopt3NoCut/unweighted_events.lhe')
photons=data.getParticlesByIDs([22,-22])
c=TCanvas()
c.Divide(2,2)

c_mom=TCanvas()
c_mom.Divide(2,2)

hist_photon_theta=TH1F("theta_photon", "Photon Theta",1000,0,1.5)
hist_photon_pt =TH1F("photon pt", "Photon Pt",100,0,1)
hist_EvTheta=TH2F("Photon Energy v Theta", "Photon Energy v Theta",
                100,0,0.5,100,0,5)
hist_phi=TH1F("phi_photon", "Photon Phi",100,-math.pi, math.pi)
hist_Pz_out=TH1F("P_{z} ", "Photon P_{z} ", 100,-1,5)
hist_Px_out=TH1F("P_{x}", "Photon P_{x} ", 100,-1,1)
hist_Py_out=TH1F("P_{y}", "Photon P_{y} ", 100,-1,1)

for g in photons:
    #theta = math.atan(g.py/g.pz)
    r = math.sqrt(g.px*g.px + g.py*g.py+g.pz*g.pz)
    theta = math.acos(g.pz/r)

    azim = math.atan(g.py/g.px)
    hist_phi.Fill(azim)
    hist_photon_theta.Fill(theta)
    hist_photon_pt.Fill(g.pt)
    print(g.energy)
    hist_EvTheta.Fill(theta,g.energy)
    hist_Pz_out.Fill(g.pz)
    hist_Px_out.Fill(g.px)
    hist_Py_out.Fill(g.py)
c.cd(1)
hist_photon_theta.Draw()
hist_photon_theta.GetXaxis().SetTitle("#theta")
c.cd(2)
hist_phi.Draw()
hist_phi.GetXaxis().SetTitle("#phi")
c.cd(3)
hist_EvTheta.GetXaxis().SetTitle("#theta")
hist_EvTheta.GetYaxis().SetTitle("E_{#gamma}")
hist_EvTheta.Draw("COLZ")
c.cd(4)
hist_photon_pt.Draw()
hist_photon_pt.GetXaxis().SetTitle("p_{t}_{#gamma}")
c.SaveAs("photon_plots.png")

c_mom.cd(1)
hist_Px_out.Draw()
hist_Px_out.GetXaxis().SetTitle("p_{x}")
c_mom.cd(2)
hist_Py_out.Draw()
hist_Py_out.GetXaxis().SetTitle("p_{y}")
c_mom.cd(3)
hist_Pz_out.Draw()
hist_Pz_out.GetXaxis().SetTitle("p_{z}")
c_mom.SaveAs("photon_mom_plots.png")
